config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :listings, :brands, :products

  root 'products#home'
  get '/contact' => 'products#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord

  has_many :products

end

app/models/listing.rb
class Listing < ApplicationRecord

  belongs_to :user

end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :brand

end

app/models/user.rb
class User < ApplicationRecord

  has_many :listings

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def index
    @brands = Brand.all
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to @brand, notice: "Company successfully added."
    else
      render 'new'
    end
  end

  def show
    @brand = Brand.find(params[:id])
  end

  def edit
  end

  def update
    if @brand.update(brand_params)
      redirect_to @brand, notice: "Update successful."
    else
    @brand = Brand.new()
      render 'edit'
    end
  end

  def destroy
    @brand.destroy
    redirect_to root_path
  end

  private

    def brand_params
      params.require(:brand).permit(:name, :about)
    end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    @listings = Listing.all.order("created_at DESC")
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)

    if @listing.save
      redirect_to @listing, notice: "Listing successfully created."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_to @listing, notice: "Update successful."
    else
      render 'edit'
    end
  end

  def destroy
    @listing.destroy
    redirect_to root_path
  end

  private

    def listing_params
      params.require(:listing).permit(:title, :description)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def home
  end

  def contact
  end

  def index
    @products = Product.all.order("created_at DESC")
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: "Product successfully added."
    else
      render 'new'
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: "Update successful."
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to root_path
  end

  private

    def product_params
      params.require(:product).permit(:name, :SKU, :price, :description, :quantity, :brand)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/brands/index.html.erb
<div class="container text-center">
  <% @brands.each do |t| %>
    <div class="col-md-4">
      <div class="text-center">
        <h2 class="center"><%= t.name %></h2>
        <h5 class="center"><%= t.about %></h3>
        <%= link_to "More Info", brand_path(t), class:"center btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/brands/show.html.erb
<h1>This is information about brand</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kalyx</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation" style="">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse d-flex justify-content-center" id="navbarColor01">
        <ul class="navbar-nav navbar-left">
          <li class="nav-item">
            <a><%= link_to "Brands", brands_path, class:'nav-link' %></a>
          </li>
          <li class="nav-item">
            <a><%= link_to "Listings", listings_path, class:'nav-link' %></a>
          </li>
          <li class="nav-item">
            <a><%= link_to "Products", products_path, class:'nav-link' %></a>
          </li>
        </ul>
        <a><%= link_to "KALYX", root_path, class:'navbar-brand navbar-center' %></a>
        <ul class="navbar-nav navbar-right">
          <% if user_signed_in? %>
              <li class="nav-item">
                <a><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:'nav-link' %></a>
              </li>
              <li class="nav-item">
                <a><%= link_to "Add Listing", new_listing_path, class:'nav-link' %></a>
              </li>
            <% else %>
              <li class="nav-item">
                <a><%= link_to "Login", new_user_session_path, class:'nav-link' %></a>
              </li>
              <li class="nav-item">
                <a><%= link_to "Signup", new_user_registration_path, class:'nav-link' %></a>
              </li>
          <% end %>
          <li class="nav-item">
            <a><%= link_to "Contact", contact_path, class:'nav-link' %></a>
          </li>
        </ul>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= simple_form_for @listing do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/listings/index.html.erb
<h1 class="text-center head-spacer">Listings</h1>

<div class="container text-center">
  <div>
    <ul class="pagination">
      <li class="page-item disabled">
        <a class="page-link" href="#">&laquo;</a>
      </li>
      <li class="page-item active">
        <a class="page-link" href="#">1</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">2</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">3</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">4</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">5</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">&raquo;</a>
      </li>
    </ul>
  </div>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Posted</th>
        </tr>
      </thead>
      <% @listings.each do |t| %>
      <tbody>
        <tr class="table-default">
          <td><%= link_to t.title, listing_path(t) %></td>
          <td><%= link_to t.description, listing_path(t) %></td>
          <td><%= link_to t.created_at, listing_path(t) %></td>
        </tr>
      </tbody>
      <% end %>
    </table>

      <div>
        <ul class="pagination">
          <li class="page-item disabled">
            <a class="page-link" href="#">&laquo;</a>
          </li>
          <li class="page-item active">
            <a class="page-link" href="#">1</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">2</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">3</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">4</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">5</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">&raquo;</a>
          </li>
        </ul>
      </div>
</div>

app/views/listings/new.html.erb
<%= render 'form' %>

app/views/listings/show.html.erb
<h1 class="text-center">Product Description of <%= @listing.title %></h1>

<div class="col-md-6 col-md-offset-3 text-center">
  <%= @listing.title %><br />
  <%= @listing.description %><br />
  <%= link_to "Back", listings_path, class:'btn btn-primary' %>
</div>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
  <%= f.input :name %>
  <%= f.input :SKU %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.input :quantity %>
  <%= f.input :brand %>
  <%= f.button :submit %>
<% end %>

app/views/products/contact.html.erb
<div class="text-center container">
  <h1 class="head-spacer">Contact Us</h1>

  <h3>Interested in growing your business and expanding your network?</h3>
</div>

app/views/products/edit.html.erb
<h1>Make changes to your product.</h1>

app/views/products/home.html.erb
<div class="bg-image">
  <div class="jumbotron-text container d-flex flex-row justify-content-center">
    <div class="text-left h7">
      <span class="green">KALYX</span>
      HAS
      ARRIVED
    </div>

    <div class="text-right h7">
      AND
      YOU'RE
      <span class="pink">INVITED</span>
    </div>
  </div>
</div>







  <!-- <h1>Transforming the business of cannabis.</h1>
  <h3>
    Kalyx serves thousands of patients and businesses worldwide. <br />
    Connect with your international cannabis community today.
  </h3> -->


<%= stylesheet_link_tag '/assets/stylesheets/application.scss'%>
<div id="particles-js"></div>
<%= javascript_include_tag 'particles', 'application'%>

app/views/products/index.html.erb
<h1 class="text-center head-spacer">Products</h1>

<div class="container">
  <div class="container col-md-3">
    <div class="list-group">
      <% @products.each do |t| %>
      <a><%= link_to t.brand, product_path(t), class:'list-group-item list-group-item-action' %></a>
      <% end %>
    </div>
  </div>

  <div class="container col-md-9 text-center">
    <% @products.each do |t| %>
      <div class="col-md-4">
        <div class="text-center">
          <h2 class="center"><%= t.name %></h2>
          <h5 class="center"><%= t.description %></h3>
          <%= link_to "More Info", product_path(t), class:"center btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>

</div>



<!-- <% @products.each do |t| %>
  <div class="card border-success mb-3" style="max-width: 20rem;">
    <div class="card-header"><%= t.name %></div>
    <div class="card-body text-success">
      <h4 class="card-title"><%= t.brand %></h4>
      <p class="card-text"><%= t.description %></p>
    </div>
  </div>
<% end %> -->

app/views/products/new.html.erb
<h1>Add your new product.</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1 class="text-center">Product Description of <%= @product.name %></h1>

<div class="col-md-6 col-md-offset-3 text-center">
  <%= @product.name %><br />
  <%= @product.SKU %><br />
  <%= @product.price %><br />
  <%= @product.description %><br />
  <%= @product.quantity %><br />
  <%= @product.brand %><br />

  <%= link_to "Back", products_path, class:'btn btn-primary' %>
</div>